kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-scraper
rules:
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routers/metrics
      - routers/federate
  - verbs:
      - get
    apiGroups:
      - image.openshift.io
    resources:
      - registry/metrics
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints
      - pods
      - services
      - namespaces
