apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mnist-predictor
  namespace: modelmesh-testing
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    create-route: "True"
    argocd.argoproj.io/sync-wave: "2"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storage:
        key: s3storage
        path: mnist-svm.joblib
