apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: my-project
spec:
  encryptedData:
    s3secret: AgCM4YYn+ayRHDKknyc9yWcCVhP/nuaYo698SVZ17OzCFEEokhkJNorvjOpHIg2C4SqZB64+5kKdf5/9BWpmEgsXSNaBoPjg51MmtW2de6zYmey13sC1iZGTmA64zxf9dQgtpO9XSWcAr71Kb4xuHQfdXuKSDwaQFo/LxIXuyMOnhE9eq6oxeIqp02j+KgadwFkpdfIBnBcNV+kcQ5kvHz5UkeCM4W8JaCPt57gt6ZMR1fyiMBc8mtu7eLAYSE4CsMZ9eJcwdjASgh5PAiZxfZ6C2fDSIknZbhTx1IMtXeMBPMm7mBDXNsixfnkFQ7X/0rTzeL8GDgjeHSNF3/Ph9VDt/7kZko4fMBfqOgvsfn+nRWyAQCLz2HO4cqkll6SrUObYTMO1H/VvaLJizLwyQUXY5WXdiSXZHubYxyMwQvdrPi47JhlIoWMWoz8DmtcrgLvFccs6VJH5l5hbmRf37LcCMwY3Wnip6aWSjvoaxHIQwQ1niBMm6JEDFnE4if5MHxnR1AHXYOjOno1TlRnthFH0JKSmceuBoE4LiPYIb7QgJEeUKXwkuxDVQSFV6MOtda+CnySZODTExbmhkQ4bnz5IePOkLKuyg3IGszVunYsO3XK0Qhny6SRH8XN+fXlXUpK2OChPQW/ddO2PgTHFAJpqBXp4Mvi8SVml37lqNPdP6fkQNYa3BV76dA44Tb8e0fX6g2JLBlUYyj8SHmZCtGKYVqtiwi3dAfx7HuPSR04/DKcpBWNNOMlX/QCplhtjImWUOOAwZC7DpMbfG92XPrCSWovub94KjuWQuQlPHfWc7ug+Bc2xgUEdC/XQRpAlrMrqRXaOLCAnccM41S8PYr82mhQCb3a+Q6aGDo/shMposrkJp4u8hc/+U9nd3Ew2Ax5FrstTDDMRPSanWD8883f3JOnHvNtk57IcZC7aiUpaFOE1n+/UzekA8/TQXXkYedY3N16tN5Lu7OOC14elZQy3NB23+IL3vptc44LOB/ghDpY5sRipN2F5DMKwD2o8
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:s3storage: {}
          f:type: {}
        manager: Mozilla
        operation: Update
        time: "2022-11-22T15:17:22Z"
      name: my-secret
      namespace: my-project
    type: Opaque

