apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
  annotations:
   argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    prometheus-additional.yaml: AgC65KO/wucyadBSs+G2ADm6yd6ES0M0uG7b/8aeYEA3geEOheIcAK1tV0w5auLTuolQBfqHDLUq8+9VGmjGQNPZt/LbfnRpeoWxth2eiukdXMYR7gGZ3qlBopM/i4ARtJIlismzwWh8AAS7jIs6JTkKDZHCtJBJdfxbUj2HGa6ITQA4HyNTJ8B+bGDvY3C1l1Yg2+MWr97LwS9W/M3rJYClF+6ypgGovBgDbuEKLd4JWgE8NZbmMg7LJc8/1h9Q9BHLS4r6ES1LIttrJums9fh587F0zuD/OiWiwV96J6YnxyDl3umgy8+eu0xJo7uiS0JIkN1wKmirG6+QUbOBR8oGNRgCcGetZYCMQhKfI71QtLWnCvX9zmI17EkCzlLZ5INaG8SMagjs7KmAoprY71R+efcHmcGHdVOVt6DjcVF5ywycTyRa97JF5NnFJWA8L+q2KLT5W5rgCM/8lDSCo445gvo9RzP4ytWEIfsTvSKjsBBMPiILl8U1TrNl6TaRp0mvaJyA0ac6l4SMEP6DgPpb5JgXs6z6kIYb2qXYRq1PxsbNgyKqeJZEFu22MfYZRqfjbgey4crgMFQCn7mEhUaMLXEli/zmA4jlG5NFzG4+O/Qgt6DWqKmSstSRSRgm7nJtdwy/ErDaFe1Ro5Gy/rI9cVlaCtnLQY3qquHFHmGgQ+2gkl8hgiNFWGB1Ih8PZqq9dp+dP6YPu0KdKKF7TwOcTDDHvGt5kjOK9Oi/SpAGkgrQ1I5hsBn1Itrawd9u998/DWeRlSU/Rw+9YvHGfb/QpOT9INYKV6eEIsjfYYgCQ703+/btanQXCzz76TYN2jl1/iUQMg8Ci0Fh48mcbtyP90Ucu1WaiNaZIu5ADIb38mhlPA==
  template:
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:prometheus-additional.yaml: {}
          f:type: {}
        manager: oc
        operation: Update
        time: "2022-11-23T16:47:33Z"
      name: additional-scrape-configs
      namespace: monitoring
    type: Opaque

